[build-system]
requires = ["setuptools", "Cython"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.exclude-package-data]
graduate_design = [
    "utils/cython_lib/*.c"
]

[tool.jedi]
venv = 'ai'

[tool.ruff]
line-length = 80
target-version = 'py39'
